0-9=0-9
100_days=100 days
10_days=10 days
110_days=110 days
120_days=120 days
130_days=130 days
140_days=140 days
14_days=14 Days
150_days=150 days
180_days=180 days
1_day=1 day
1_day_from_expiration_desktop_image=https://keeper-email-images.s3.amazonaws.com/kb3036/consumer_trial/expiring_3/en_US/1_day_from_expiration_desktop.png
1_day_from_expiration_mobile_image=https://keeper-email-images.s3.amazonaws.com/kb3036/consumer_trial/expiring_3/en_US/1_day_from_expiration_mobile.png
1_free_upload_remaining=1 Free Upload Remaining
1_hour=1 hour
1_user=1 User
1_week=1 week
20_days=20 days
24_hours=24 hours
24_hours_only=24 Hours Only
256_bit_aes_data=256-Bit AES Storage Encrypted Data
2FA_required_question=2FA Required?
2fa_Inactive=2FA Inactive
2fa_allowed_methods=Allowed Two Factor Methods
2fa_changed=Two Factor Changed
2fa_copied_to_clipboard=2FA code copied to clipboard.
2fa_disabled=2FA Disabled
2fa_frequency=2FA Frequency
2fa_method=2FA Method
2fa_method_required=Two-Factor Method Required
2fa_method_updated=Two-Factor method updated
2fa_no_enforcement=Allow user to set
2fa_offline_access_enabled_message=Offline Access is currently enabled. Two-Factor authentication methods will be bypassed when logging in offline.
2fa_offline_access_enabled_title=Offline Access Enabled
2fa_please_select=A 2FA Method is required by your Keeper Administrator. Select a method from the options below.
2fa_prompt_frequency=Two-Factor Prompt Frequency
2fa_prompt_frequency_tooltip=The default prompt frequency for User defined is Every login until the user changes it.
2fa_req_every_12_hrs=Require every 12 hours
2fa_req_every_24_hrs=Require every 24 hours
2fa_req_every_30_days=Require every 30 days
2fa_req_every_login=Require every login
30_day_trend=30-Day Trend
30_days=30 days
3_days_from_expiration_desktop_image=https://keeper-email-images.s3.amazonaws.com/kb3036/consumer_trial/expiring_2/en_US/3_days_from_expiration_desktop.png
3_days_from_expiration_mobile_image=https://keeper-email-images.s3.amazonaws.com/kb3036/consumer_trial/expiring_2/en_US/3_days_from_expiration_mobile.png
40_days=40 days
4_9_stars=4.9 Stars
4_hours=4 hours
5080_rotate_password=Rotate password
508_2fa_duo_logo=2fa duo logo
508_2fa_keys_logo=2fa security keys logo
new_string_group1=This is a new string for group one.
new_string_group2=This is a new string for group two.
new_string2_group1=This is a second new string for group one.